language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: d93KGooUL8s3CE+DrI0/cFrBlaREL5DWoknxw3qtyIh9bJACTrP5P7RyYrrF3zWAHz6BeY8jbb2EAWJISejTb+KaQvGosGi8Uuw3934Soj+svfhAtqkuNoRnlQTKi6B6Cwvf3+E3aPyg+klo5DLQxwN1PcCnupG9gQTeuGVdyjdV419kKqU3I/KZJ02QYFFZiy1WTJcIC2JgIRPmnJV6p7KtQucUKu3oKQIJeWGIRlgR30RuQ20MhuO0gdwtTLOhPET7xSs718YbsUSRTnmBILW/FfmLZcmTLQ/Avre6Kaf3yUIQrCgz4p0dooTJasEDxk4ZdG19ZgvxnZED2krXb5iIHQzjLdWMFqEzW54dex8o+d5ACGGVj2+5iS334oI/jsxcaVACRjUUi6PBfLtmya+07BJ7wMaZwUSFJ3cQXCtFH5lDAUOX/OBPrEJynwOCsC252BvKBlSvwyT1UVmQU8HYQ3U8ddXJT0RYz2Gi6WKOjalnvsqkeQ+miCyYxFLKoINGd1A5Inqznq7LKwp5OhMvCnSInb+gpI1Hwc4RcFRbvRFQ6797PxOHVWyX2Kq//yOXSqt8DnF9FCCdaUWKNiDhAiHqVCn6VVnkkZdEwdl2tG1A0FfTpY3lZp45xeTRjYrZ9Y4K9zWG9eojxxNjGKwlYVSYhfaWrKFLpOr7wSU=
  app: lit-badlands-21236
  on:
    repo: thisIsMeHello/canvassingapp
